-- MySQL Script generated by MySQL Workbench
-- Thu Oct 30 11:54:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Memory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Memory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Memory` DEFAULT CHARACTER SET utf8 ;
USE `Memory` ;

-- -----------------------------------------------------
-- Table `Memory`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Role` (
  `id_Role` INT NOT NULL AUTO_INCREMENT,
  `Name_role_Unique` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Role`),
  UNIQUE INDEX `Name_role_Unique_UNIQUE` (`Name_role_Unique` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Category` (
  `id_Category` INT NOT NULL AUTO_INCREMENT,
  `Name_Unique` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Category`),
  UNIQUE INDEX `Name_Unique_UNIQUE` (`Name_Unique` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Project` (
  `id_Project` INT NOT NULL AUTO_INCREMENT,
  `Name_Unique` VARCHAR(50) NOT NULL,
  `Description` TEXT(1000) NOT NULL,
  `Date_of_creation` DATE NOT NULL,
  `Archive_date` DATE NOT NULL,
  `Category_id_Category` INT NOT NULL,
  PRIMARY KEY (`id_Project`),
  UNIQUE INDEX `Name_Unique_UNIQUE` (`Name_Unique` ASC) VISIBLE,
  INDEX `fk_Project_Category1_idx` (`Category_id_Category` ASC) VISIBLE,
  CONSTRAINT `fk_Project_Category1`
    FOREIGN KEY (`Category_id_Category`)
    REFERENCES `Memory`.`Category` (`id_Category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Task` (
  `id_Task` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(50) NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  `Date_of_creation` DATE NOT NULL,
  `Due_date` DATE NOT NULL,
  `Status` ENUM('to do', 'on going', 'done') NULL,
  `Project_id_Project` INT NOT NULL,
  PRIMARY KEY (`id_Task`),
  INDEX `fk_Task_Project1_idx` (`Project_id_Project` ASC) VISIBLE,
  CONSTRAINT `fk_Task_Project1`
    FOREIGN KEY (`Project_id_Project`)
    REFERENCES `Memory`.`Project` (`id_Project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`User` (
  `id_User` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Email_Unique` VARCHAR(200) NOT NULL,
  `Password` VARCHAR(250) NOT NULL,
  `Role_id_Role` INT NOT NULL,
  `Task_id_Task` INT NOT NULL,
  PRIMARY KEY (`id_User`),
  INDEX `fk_User_Role1_idx` (`Role_id_Role` ASC) VISIBLE,
  INDEX `fk_User_Task1_idx` (`Task_id_Task` ASC) VISIBLE,
  UNIQUE INDEX `Email_Unique_UNIQUE` (`Email_Unique` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_id_Role`)
    REFERENCES `Memory`.`Role` (`id_Role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Task1`
    FOREIGN KEY (`Task_id_Task`)
    REFERENCES `Memory`.`Task` (`id_Task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Administrator` (
  `id_Administrator` INT NOT NULL,
  PRIMARY KEY (`id_Administrator`),
  CONSTRAINT `Fk_admin_user`
    FOREIGN KEY (`id_Administrator`)
    REFERENCES `Memory`.`User` (`id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Permission` (
  `id_Permission` INT NOT NULL AUTO_INCREMENT,
  `Wording_unique` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Permission`),
  UNIQUE INDEX `Wording_unique_UNIQUE` (`Wording_unique` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Notification` (
  `id_Notification` INT NOT NULL AUTO_INCREMENT,
  `Date_of_creation` DATE NOT NULL,
  `Content` VARCHAR(200) NOT NULL,
  `Is_read` TINYINT NOT NULL DEFAULT 0,
  `User_id_User` INT NOT NULL,
  PRIMARY KEY (`id_Notification`),
  INDEX `fk_Notification_User_idx` (`User_id_User` ASC) VISIBLE,
  CONSTRAINT `fk_Notification_User`
    FOREIGN KEY (`User_id_User`)
    REFERENCES `Memory`.`User` (`id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Tag` (
  `id_Tag` INT NOT NULL AUTO_INCREMENT,
  `Name_Unique` VARCHAR(50) NOT NULL,
  `Content` TEXT(50) NOT NULL,
  PRIMARY KEY (`id_Tag`),
  UNIQUE INDEX `Name_Unique_UNIQUE` (`Name_Unique` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Note` (
  `id_Note` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(50) NOT NULL,
  `Content` TEXT(500) NOT NULL,
  `Date_of_creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Tag_id_Tag` INT NOT NULL,
  `Category_id_Category` INT NOT NULL,
  `Project_id_Project` INT NOT NULL,
  PRIMARY KEY (`id_Note`),
  INDEX `fk_Note_Tag1_idx` (`Tag_id_Tag` ASC) VISIBLE,
  INDEX `fk_Note_Category1_idx` (`Category_id_Category` ASC) VISIBLE,
  INDEX `fk_Note_Project1_idx` (`Project_id_Project` ASC) VISIBLE,
  CONSTRAINT `fk_Note_Tag1`
    FOREIGN KEY (`Tag_id_Tag`)
    REFERENCES `Memory`.`Tag` (`id_Tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_Category1`
    FOREIGN KEY (`Category_id_Category`)
    REFERENCES `Memory`.`Category` (`id_Category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_Project1`
    FOREIGN KEY (`Project_id_Project`)
    REFERENCES `Memory`.`Project` (`id_Project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Comment` (
  `id_Comment` INT NOT NULL AUTO_INCREMENT,
  `Content` TEXT(500) NOT NULL,
  `Date_of_creation` DATETIME NOT NULL,
  `User_id_User` INT NOT NULL,
  `Note_id_Note` INT NOT NULL,
  PRIMARY KEY (`id_Comment`),
  INDEX `fk_Comment_User1_idx` (`User_id_User` ASC) VISIBLE,
  INDEX `fk_Comment_Note1_idx` (`Note_id_Note` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_id_User`)
    REFERENCES `Memory`.`User` (`id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Note1`
    FOREIGN KEY (`Note_id_Note`)
    REFERENCES `Memory`.`Note` (`id_Note`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Report` (
  `id_Report` INT NOT NULL AUTO_INCREMENT,
  `Date_of_creation` DATE NOT NULL,
  `Content` TEXT(1500) NOT NULL,
  `Project_id_Project` INT NOT NULL,
  PRIMARY KEY (`id_Report`),
  INDEX `fk_Report_Project1_idx` (`Project_id_Project` ASC) VISIBLE,
  CONSTRAINT `fk_Report_Project1`
    FOREIGN KEY (`Project_id_Project`)
    REFERENCES `Memory`.`Project` (`id_Project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Competence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Competence` (
  `id_Competence` INT NOT NULL AUTO_INCREMENT,
  `Wording_Unique` VARCHAR(70) NOT NULL,
  `User_id_User` INT NOT NULL,
  PRIMARY KEY (`id_Competence`),
  UNIQUE INDEX `Wording_Unique_UNIQUE` (`Wording_Unique` ASC) VISIBLE,
  INDEX `fk_Competence_User1_idx` (`User_id_User` ASC) VISIBLE,
  CONSTRAINT `fk_Competence_User1`
    FOREIGN KEY (`User_id_User`)
    REFERENCES `Memory`.`User` (`id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Is_associated`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Is_associated` (
  `Role_id_Role` INT NOT NULL,
  `Permission_id_Permission` INT NOT NULL,
  PRIMARY KEY (`Role_id_Role`, `Permission_id_Permission`),
  INDEX `fk_Role_has_Permission_Permission1_idx` (`Permission_id_Permission` ASC) VISIBLE,
  INDEX `fk_Role_has_Permission_Role1_idx` (`Role_id_Role` ASC) VISIBLE,
  CONSTRAINT `fk_Role_has_Permission_Role1`
    FOREIGN KEY (`Role_id_Role`)
    REFERENCES `Memory`.`Role` (`id_Role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role_has_Permission_Permission1`
    FOREIGN KEY (`Permission_id_Permission`)
    REFERENCES `Memory`.`Permission` (`id_Permission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Share`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Share` (
  `User_id_User` INT NOT NULL,
  `Note_id_Note` INT NOT NULL,
  PRIMARY KEY (`User_id_User`, `Note_id_Note`),
  INDEX `fk_User_has_Note_Note1_idx` (`Note_id_Note` ASC) VISIBLE,
  INDEX `fk_User_has_Note_User1_idx` (`User_id_User` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Note_User1`
    FOREIGN KEY (`User_id_User`)
    REFERENCES `Memory`.`User` (`id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Note_Note1`
    FOREIGN KEY (`Note_id_Note`)
    REFERENCES `Memory`.`Note` (`id_Note`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Memory`.`Manage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Memory`.`Manage` (
  `User_id_User` INT NOT NULL,
  `Project_id_Project` INT NOT NULL,
  PRIMARY KEY (`User_id_User`, `Project_id_Project`),
  INDEX `fk_User_has_Project_Project1_idx` (`Project_id_Project` ASC) VISIBLE,
  INDEX `fk_User_has_Project_User1_idx` (`User_id_User` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Project_User1`
    FOREIGN KEY (`User_id_User`)
    REFERENCES `Memory`.`User` (`id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Project_Project1`
    FOREIGN KEY (`Project_id_Project`)
    REFERENCES `Memory`.`Project` (`id_Project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
